all :
	scrapy crawl economiaAzteca -t csv
	scrapy crawl economiaElEconomista -t csv
	scrapy crawl laJornadaEconomia -t csv
	scrapy crawl economiaPrensa -t csv
	scrapy crawl economiaAristegui -t csv
	scrapy crawl economiaLaPrensa -t csv
