all:

	python AlgoritmosEntrenamiento.py 'NaiveBayes' 3 '../../Corpus/Balanceado700.txt' 1
	python AlgoritmosEntrenamiento.py 'NaiveBayes' 5 '../../Corpus/Balanceado700.txt' 1
	python AlgoritmosEntrenamiento.py 'NaiveBayes' 7 '../../Corpus/Balanceado700.txt' 1

	python AlgoritmosEntrenamiento.py 'RegresionLogistica' 3 '../../Corpus/Balanceado700.txt' 1
	python AlgoritmosEntrenamiento.py 'RegresionLogistica' 5 '../../Corpus/Balanceado700.txt' 1
	python AlgoritmosEntrenamiento.py 'RegresionLogistica' 7 '../../Corpus/Balanceado700.txt' 1
	
	python AlgoritmosEntrenamiento.py 'RandomForest' 3 '../../Corpus/Balanceado700.txt' 1
	python AlgoritmosEntrenamiento.py 'RandomForest' 5 '../../Corpus/Balanceado700.txt' 1
	python AlgoritmosEntrenamiento.py 'RandomForest' 7 '../../Corpus/Balanceado700.txt' 1

	
	python AlgoritmosEntrenamiento.py 'MSV' 3 '../../Corpus/Balanceado700.txt' 1
	python AlgoritmosEntrenamiento.py 'MSV' 5 '../../Corpus/Balanceado700.txt' 1
	python AlgoritmosEntrenamiento.py 'MSV' 7 '../../Corpus/Balanceado700.txt' 1


	python AlgoritmosEntrenamiento.py 'NaiveBayes' 3 '../../Corpus/Balanceado700.txt' 0
	python AlgoritmosEntrenamiento.py 'NaiveBayes' 5 '../../Corpus/Balanceado700.txt' 0
	python AlgoritmosEntrenamiento.py 'NaiveBayes' 7 '../../Corpus/Balanceado700.txt' 0

	python AlgoritmosEntrenamiento.py 'RegresionLogistica' 3 '../../Corpus/Balanceado700.txt' 0
	python AlgoritmosEntrenamiento.py 'RegresionLogistica' 5 '../../Corpus/Balanceado700.txt' 0
	python AlgoritmosEntrenamiento.py 'RegresionLogistica' 7 '../../Corpus/Balanceado700.txt' 0
	
	python AlgoritmosEntrenamiento.py 'RandomForest' 3 '../../Corpus/Balanceado700.txt' 0
	python AlgoritmosEntrenamiento.py 'RandomForest' 5 '../../Corpus/Balanceado700.txt' 0
	python AlgoritmosEntrenamiento.py 'RandomForest' 7 '../../Corpus/Balanceado700.txt' 0

	
	python AlgoritmosEntrenamiento.py 'MSV' 3 '../../Corpus/Balanceado700.txt' 0
	python AlgoritmosEntrenamiento.py 'MSV' 5 '../../Corpus/Balanceado700.txt' 0
	python AlgoritmosEntrenamiento.py 'MSV' 7 '../../Corpus/Balanceado700.txt' 0
