all:

	python GridSearch.py 'NaiveBayes' '../../Corpus/Procesado/CorpusTrain_3150.txt' 1
	python GridSearch.py 'RegresionLogistica' '../../Corpus/Procesado/CorpusTrain_3150.txt' 1
	python GridSearch.py 'MSV' '../../Corpus/Procesado/CorpusTrain_3150.txt' 1
	python GridSearch.py 'RandomForest' '../../Corpus/Procesado/CorpusTrain_3150.txt' 1
