all:

	python ValidacionCruzada.py 'NaiveBayes' 3 '../../Corpus/Procesado/Balanceado_700.txt' 1
	python ValidacionCruzada.py 'NaiveBayes' 5 '../../Corpus/Procesado/Balanceado_700.txt' 1
	python ValidacionCruzada.py 'NaiveBayes' 7 '../../Corpus/Procesado/Balanceado_700.txt' 1

	python ValidacionCruzada.py 'RegresionLogistica' 3 '../../Corpus/Procesado/Balanceado_700.txt' 1
	python ValidacionCruzada.py 'RegresionLogistica' 5 '../../Corpus/Procesado/Balanceado_700.txt' 1
	python ValidacionCruzada.py 'RegresionLogistica' 7 '../../Corpus/Procesado/Balanceado_700.txt' 1
	
	python ValidacionCruzada.py 'RandomForest' 3 '../../Corpus/Procesado/Balanceado_700.txt' 1
	python ValidacionCruzada.py 'RandomForest' 5 '../../Corpus/Procesado/Balanceado_700.txt' 1
	python ValidacionCruzada.py 'RandomForest' 7 '../../Corpus/Procesado/Balanceado_700.txt' 1

	
	python ValidacionCruzada.py 'MSV' 3 '../../Corpus/Procesado/Balanceado_700.txt' 1
	python ValidacionCruzada.py 'MSV' 5 '../../Corpus/Procesado/Balanceado_700.txt' 1
	python ValidacionCruzada.py 'MSV' 7 '../../Corpus/Procesado/Balanceado_700.txt' 1


	python ValidacionCruzada.py 'NaiveBayes' 3 '../../Corpus/Procesado/Balanceado_700.txt' 0
	python ValidacionCruzada.py 'NaiveBayes' 5 '../../Corpus/Procesado/Balanceado_700.txt' 0
	python ValidacionCruzada.py 'NaiveBayes' 7 '../../Corpus/Procesado/Balanceado_700.txt' 0

	python ValidacionCruzada.py 'RegresionLogistica' 3 '../../Corpus/Procesado/Balanceado_700.txt' 0
	python ValidacionCruzada.py 'RegresionLogistica' 5 '../../Corpus/Procesado/Balanceado_700.txt' 0
	python ValidacionCruzada.py 'RegresionLogistica' 7 '../../Corpus/Procesado/Balanceado_700.txt' 0
	
	python ValidacionCruzada.py 'RandomForest' 3 '../../Corpus/Procesado/Balanceado_700.txt' 0
	python ValidacionCruzada.py 'RandomForest' 5 '../../Corpus/Procesado/Balanceado_700.txt' 0
	python ValidacionCruzada.py 'RandomForest' 7 '../../Corpus/Procesado/Balanceado_700.txt' 0

	
	python ValidacionCruzada.py 'MSV' 3 '../../Corpus/Procesado/Balanceado_700.txt' 0
	python ValidacionCruzada.py 'MSV' 5 '../../Corpus/Procesado/Balanceado_700.txt' 0
	python ValidacionCruzada.py 'MSV' 7 '../../Corpus/Procesado/Balanceado_700.txt' 0
